using System;

namespace Division.Service
{
    public class Logic
    {
        public static void ThrowException()
        {
            throw new Exception("Ha ocurrido una excepción personalizada.");
        }
    }
}
